### ISSUE TITLE
The Oasis Seed Node Address provided in the network parameter is invalid

### ISSUE THREAD

**Issue by chriswsq** [oasisprotocol/docs-gitbook#10]
The Oasis Seed Node Address provided in the network parameter is invalid
![image](https://user-images.githubusercontent.com/45168294/97963562-56c56400-1df2-11eb-81ed-1de5fa0a1264.png)

**Comment by kostko** [comment]
The address is correct, but for some reason you wrapped it in `{{ ... }}`. Those only denote placeholders used in documentation and should not be present after you substitute the address. Just remove the braces and it should work.

**Comment by chriswsq** [comment]
> 该地址是正确的，但是由于某种原因您将其包装在中`{{ ... }}`。这些仅表示文档中使用的占位符，在您替换地址后不应再出现。只需取下牙套即可。

very much
